# Generated by Django 4.1.3 on 2022-11-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_completed_remove_task_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completed',
        ),
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
